// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yobzbfapxavfdtznhpba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvYnpiZmFweGF2ZmR0em5ocGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NDE0NzIsImV4cCI6MjA2NjExNzQ3Mn0.MXU7FlfLcgIEI1OwrdLlacUMqNMYYqYEcD210X594ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);